# Generated by Django 6.0.5 on 2026-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Study Groups', '📚 Study Groups'), ('Events', '🎉 Events'), ('Housing', '🏠 Housing'), ('Clubs', '⭐ Clubs'), ('General', '📌 General')], default='General', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
